//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.DataRepositoryServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataRepositoryServiceReference.IDataRepositoryService")]
    public interface IDataRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataRepositoryService/AddEntity", ReplyAction="http://tempuri.org/IDataRepositoryService/AddEntityResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.Worker))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.Crew))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.CrewMember))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.Assignment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.Model.Shift))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.Model.WorkingDay))]
        Common.model.IdentifiedObject[] AddEntity(Common.model.IdentifiedObject _entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataRepositoryService/RemoveEntity", ReplyAction="http://tempuri.org/IDataRepositoryService/RemoveEntityResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.Worker))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.Crew))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.CrewMember))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.Assignment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.Model.Shift))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.Model.WorkingDay))]
        Common.model.IdentifiedObject[] RemoveEntity(Common.model.IdentifiedObject _entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataRepositoryService/GetEntityById", ReplyAction="http://tempuri.org/IDataRepositoryService/GetEntityByIdResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.Worker))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.Crew))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.CrewMember))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.Assignment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.Model.Shift))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.Model.WorkingDay))]
        Common.model.IdentifiedObject GetEntityById(Common.EntityType _type, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataRepositoryService/GetEntityByType", ReplyAction="http://tempuri.org/IDataRepositoryService/GetEntityByTypeResponse")]
        Common.model.IdentifiedObject[] GetEntityByType(Common.EntityType _type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataRepositoryService/GetUserByUsername", ReplyAction="http://tempuri.org/IDataRepositoryService/GetUserByUsernameResponse")]
        Common.model.User GetUserByUsername(string _username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataRepositoryService/UpdateEntity", ReplyAction="http://tempuri.org/IDataRepositoryService/UpdateEntityResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.Worker))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.Crew))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.CrewMember))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.Assignment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.model.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.Model.Shift))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Common.Model.WorkingDay))]
        void UpdateEntity(Common.model.IdentifiedObject _entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataRepositoryService/CreateWorkingDays", ReplyAction="http://tempuri.org/IDataRepositoryService/CreateWorkingDaysResponse")]
        int CreateWorkingDays();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataRepositoryService/GetDayOfYear", ReplyAction="http://tempuri.org/IDataRepositoryService/GetDayOfYearResponse")]
        Common.Model.WorkingDay GetDayOfYear(System.DateTime _day);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataRepositoryServiceChannel : TestClient.DataRepositoryServiceReference.IDataRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataRepositoryServiceClient : System.ServiceModel.ClientBase<TestClient.DataRepositoryServiceReference.IDataRepositoryService>, TestClient.DataRepositoryServiceReference.IDataRepositoryService {
        
        public DataRepositoryServiceClient() {
        }
        
        public DataRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Common.model.IdentifiedObject[] AddEntity(Common.model.IdentifiedObject _entity) {
            return base.Channel.AddEntity(_entity);
        }
        
        public Common.model.IdentifiedObject[] RemoveEntity(Common.model.IdentifiedObject _entity) {
            return base.Channel.RemoveEntity(_entity);
        }
        
        public Common.model.IdentifiedObject GetEntityById(Common.EntityType _type, string id) {
            return base.Channel.GetEntityById(_type, id);
        }
        
        public Common.model.IdentifiedObject[] GetEntityByType(Common.EntityType _type) {
            return base.Channel.GetEntityByType(_type);
        }
        
        public Common.model.User GetUserByUsername(string _username) {
            return base.Channel.GetUserByUsername(_username);
        }
        
        public void UpdateEntity(Common.model.IdentifiedObject _entity) {
            base.Channel.UpdateEntity(_entity);
        }
        
        public int CreateWorkingDays() {
            return base.Channel.CreateWorkingDays();
        }
        
        public Common.Model.WorkingDay GetDayOfYear(System.DateTime _day) {
            return base.Channel.GetDayOfYear(_day);
        }
    }
}
