//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UIClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add assignment.
        /// </summary>
        public static string BUTTON_ADD_ASSIGNMENT {
            get {
                return ResourceManager.GetString("BUTTON_ADD_ASSIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add crew.
        /// </summary>
        public static string BUTTON_ADD_CREW {
            get {
                return ResourceManager.GetString("BUTTON_ADD_CREW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add member.
        /// </summary>
        public static string BUTTON_ADD_MEMBER {
            get {
                return ResourceManager.GetString("BUTTON_ADD_MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string BUTTON_LOGIN {
            get {
                return ResourceManager.GetString("BUTTON_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string BUTTON_OK {
            get {
                return ResourceManager.GetString("BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update member.
        /// </summary>
        public static string BUTTON_UPDATE_MEMBER {
            get {
                return ResourceManager.GetString("BUTTON_UPDATE_MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string CAPTION_ERROR {
            get {
                return ResourceManager.GetString("CAPTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned time:.
        /// </summary>
        public static string LABEL_ASSIGNED_TIME {
            get {
                return ResourceManager.GetString("LABEL_ASSIGNED_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment workers.
        /// </summary>
        public static string LABEL_ASSIGNMENT_WORKERS {
            get {
                return ResourceManager.GetString("LABEL_ASSIGNMENT_WORKERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliable workers.
        /// </summary>
        public static string LABEL_AVALIABLE_WORKERS {
            get {
                return ResourceManager.GetString("LABEL_AVALIABLE_WORKERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew:.
        /// </summary>
        public static string LABEL_CREW {
            get {
                return ResourceManager.GetString("LABEL_CREW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew Name:.
        /// </summary>
        public static string LABEL_CREW_NAME {
            get {
                return ResourceManager.GetString("LABEL_CREW_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        public static string LABEL_DURATION {
            get {
                return ResourceManager.GetString("LABEL_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address:.
        /// </summary>
        public static string LABEL_EMAIL {
            get {
                return ResourceManager.GetString("LABEL_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name:.
        /// </summary>
        public static string LABEL_FAMILY_NAME {
            get {
                return ResourceManager.GetString("LABEL_FAMILY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        public static string LABEL_NAME {
            get {
                return ResourceManager.GetString("LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string LABEL_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string LABEL_PHONE {
            get {
                return ResourceManager.GetString("LABEL_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift:.
        /// </summary>
        public static string LABEL_SHIFT {
            get {
                return ResourceManager.GetString("LABEL_SHIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills:.
        /// </summary>
        public static string LABEL_SKILS {
            get {
                return ResourceManager.GetString("LABEL_SKILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dd.HH:mm].
        /// </summary>
        public static string LABEL_TIME_FORMAT {
            get {
                return ResourceManager.GetString("LABEL_TIME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role:.
        /// </summary>
        public static string LABEL_USER_TYPE {
            get {
                return ResourceManager.GetString("LABEL_USER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string LABEL_USERNAME {
            get {
                return ResourceManager.GetString("LABEL_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers:.
        /// </summary>
        public static string LABEL_WORKERS {
            get {
                return ResourceManager.GetString("LABEL_WORKERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred.
        /// </summary>
        public static string MESSAGE_ERROR {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in failed.
        /// </summary>
        public static string MESSAGE_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("MESSAGE_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to Crew Field Service Management.
        /// </summary>
        public static string TITLE_LOGIN {
            get {
                return ResourceManager.GetString("TITLE_LOGIN", resourceCulture);
            }
        }
    }
}
